apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "postgres.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
