apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mentor-backend.fullname" . }}
  labels:
    app: {{ include "mentor-backend.name" . }}
    chart: {{ include "mentor-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mentor-backend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "mentor-backend.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "mentor-backend.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecret.name | quote }}
                  key: {{ .Values.postgres.passwordSecret.key | quote }}
            - name: MINIO_ENDPOINT
              value: {{ .Values.minio.endpoint | quote }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.accessKeySecret.name | quote }}
                  key: {{ .Values.minio.accessKeySecret.key | quote }}
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretKeySecret.name | quote }}
                  key: {{ .Values.minio.secretKeySecret.key | quote }}
            - name: MINIO_REGION
              value: {{ .Values.minio.region | quote }}
            - name: MINIO_BUCKET_NAME
              value: {{ .Values.minio.bucket | quote }}
            - name: FRONTEND_ORIGIN
              value: {{ .Values.frontendOrigin | default "http://localhost:15000" | quote }}
            {{- if .Values.frontendOriginRegex }}
            - name: FRONTEND_ORIGIN_REGEX
              value: {{ .Values.frontendOriginRegex | quote }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
