apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "minio.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: 9000
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: 9001
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.consoleNodePort }}
      {{- end }}
