replicaCount: 1

image:
  # Using explicit registry reference for official PostgreSQL image
  repository: docker.io/library/postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5432
  nodePort: 30432

storage:
  size: 2Gi

postgres:
  user: monitor
  password: supersecret
  db: monitoring_db

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
